export const ASCII_COLS = 96;
export const ASCII_ROWS = 72;

export const ASCII_QUOTES: string[] = [
  'Icarus laughed as he fell.',
  'Destiny must be fulfilled.',
  'Local minima are rare in high-dimensional spaces.',
];

export const ASCII_FRAMES: string[
  [
    '                                                                                                ',
    '                                                                                                ',
    '                                       @@?                                                      ',
    '                                 `@@  q@@@d                                                     ',
    '                                 @@@@ a@k@@                                                     ',
    '                              rj @@@@@@@"@@<                                                    ',
    '                              @@@B@b@@@@(@o                                                     ',
    '                              @W@@@l@@@L[@o*                                                    ',
    '                          %@@ @@@@@ @@@m\'@@B                                                    ',
    '                          @@@@@@@@@`h@@@0@@M                                                    ',
    '                          /@W@@@z@@ }@@Cr@@                                                     ',
    '                           @@#@@-@@@/@# @@@                                                     ',
    '                           1B*@@}@@Cb@h @@@                                                     ',
    '                        @@@@@@@@ @@@d@@\'@@@                                                     ',
    '                        @@@@@@@@ @@@h@} @@@                                                     ',
    '                        @@#@@@@@@@@ x@:(@@c                                                     ',
    '                         @@ @@@@@ @@@@@@@%                                                      ',
    '                        @@@@ @@@@@@@a@B@@@@b                                                    ',
    '                        @@@@@i@@@@@@ @)@@@@@a                                                   ',
    '                       h@@C@@@@@@@@@@@@@@@@@B                                                   ',
    '                       @@@@ @@@@@@@@@M@@@@xu@B@@@                                               ',
    '                       @@@@@a@@@@@@@@@@@@@@Z#%&@@Q                                              ',
    '                      d@@@@@@@@@@@#@@@X@@@@Wh8                                                  ',
    '                      @@@@@@@@@@@@%@%@@@Bo8o&&                                                  ',
    '                      @@@@@@@@@@@%@@@@h@@B@C@@                                                  ',
    '                      @@@@@@@@@@@@@@@@&@@@@X&@                                                  ',
    '                      @@@@@@@@@@Bk@@%@M@@@@} @q                                                 ',
    '                       @@@@@@@@@@*@@UW@@@@@f/&M                                                 ',
    '                       @@@#B@@@@@#d@@%@@@@@&]@@                                                 ',
    '                        @@@@@@&@@8%%@@@@@@@@&@@@  0OCb#                                         ',
    '                        @@@@@@@%@@%@*@@@@@@J[@@@@@@@@%@@n                                       ',
    '                         @@@@@@@@@B@B8@h@8@MY@8@@@@@@@C@@@                                      ',
    '                         W@@@@@cM@@@@@%@@@@8@@@@@@Ooqkb@@@@                                     ',
    '                          q@@@@@@@@@@@@@@@@@@d@@@@@oMtZ@@@@                                     ',
    '                            @@@@@@@@@@@@@@@@@B@@@@@@@Of@@@B                                     ',
    '                            @@@@a@@@@@@@@@W@@Q@@# @@#k@@@w                                      ',
    '                             @@@@@@@B@@@@@@@WwBB   ad@@@@@                                      ',
    '                              @@@@@@@@@@@@@8@@@@r    @qq@@0                                     ',
    '                               @@@@@@@J@@@@@@@@%&m} mx  O@@@                                    ',
    '                                  @@@@@@@@@@@@_;8BC@@O   @@@                                    ',
    '                                         z@(d#@@@@@[@@d-@@B@                                    ',
    '                                         c@@@@@@@@Y%@@q@@@@@@J                                  ',
    '                                          @%@@@@@@@;)@@@@@@B@@                                  ',
    '                                        n@@@@@W *@@@@@@@@@@@W@@@\'                               ',
    '                                        @@@@@@@@@@@Mb@@@@Q@@@@@@@@                              ',
    '                                       O@@@@@@lJ@#)h@@@@@@@h@@@BW@@                             ',
    '                                       @@@@@@@@  @@@@@@@@@8M@@@@@@@@o                           ',
    '                                       @@@@@@@@@@@@@B@@@@@@a%@J@@@@@@@8                         ',
    '                                      @@X@@@@@@@@@@@@@@@%@@@@@@@@@@@@%@%                        ',
    '                                      @@L%@@@@@@W8@@@a@@@@@@@@@@@@@@@@%8                        ',
    '                                      @@@l@@@@@@@@@aI @@@@@%@@@@@@@@@@@@k                       ',
    '                                      @QM/<@@@@@@@ @+>@@@@@@@@@B@@@@#@@@@@                      ',
    '                                      @C*c[@@@@@@!>BX,@@@@@@@@@@@t@b%@@@@@@                     ',
    '                                      @@nX1 @@ @@O?@@ @@@@@M@@@@@@@@&@@@@@@@                    ',
    '                                      @@0o[_@@  @@kv@@@@@@@@@@@@@@@@@@@@@@@@B                   ',
    '                                       @%@@@@@  q@Bnu~@@@@@@%k@m@O@@@@@@M@@@@(                  ',
    '                                       @Mb@@@@  @@@@@8@@@@W@>@@ @l@@@@ @@]@@@@                  ',
    '                                       @@B@@@  B@@*%@@@@@@@@@b@.@;@@W@L!@8;@@@@                 ',
    '                                       @@@@%@0 @@ZOC@@   @@@@@@ @q@@ %@ X@m<@@@                 ',
    '                                       @@8@o@Q W@o)@@@        @@@@L@J8@q"@@_@@@8                ',
    '                                       @@*#@@ @@@@@@U         h@@@p%@b@@pJ@wi@@@                ',
    '                                        @@O@@ @@@@@@           M@@@n@<B@@#@@\'_@@                ',
    '                                        @@0@%  @@*@x             @@@@@z@@>nB8)@@@               ',
    '                                        [@@@@  B%w@~               @@@@*@@ *@@U@@`              ',
    '                                         @@B@  @@@@                  w@@@@@@@@@&@@              ',
    '                                         @Bp@W @@@                     WB @@@@@@@@              ',
    '                                         @@B@@                              -- @@@              ',
    '                                         @@@@B                                                  ',
    '                                        1@@@@%                                                  ',
    '                                           i_                                                   ',
    '                                                                                                ',
    '                                                                                                ',
  ],
  [
    '                                                                                                ',
    '                                                                                                ',
    '                                                                                                ',
    '                                                                                                ',
    '                                                                                                ',
    '                                       `l{{rj)Yz|CYLkJUn]I,                                     ',
    '                                   <[vp%@@@W@@WM%@@@%@W&Z*mLX/i:                                ',
    '                               +xp*@8@@@@qp0JZQZwCUYdYu*a8#zLo@@Wui.                            ',
    '                            ?L@@@@MdLLzYwzJwqo*c}Y/zt|JQXY#qw@@a@@@m|-                          ',
    '                         IJo8@hOCZwuZCqha@@@@@QLXfQY)m@@@WqnuQpxdZ0OCbC1i                       ',
    '                      !u#@@*QvxJa@WmMkhmvMzM@ur_c@@?{/O?#*wz>uY(Jm@o@bU/fl                      ',
    '                    +0@@d0Xxf@@@@@wbJL@@@bO*Zq@Yp@@&Lkv+-[-1?Q?j]XzU&*o?xXx_                    ',
    '                  im@&X/xXmkcM@wwhho&@@@@@@@@@@@@@@@@@@Z0M@r0XfC|@@kcxo&W@@@p]                  ',
    '                .cBmfxoOJph@MaWk@&@@@@@@@@@@@@@@@@@%okh@@@@@m?XYJ*b@@Btrwk0mpqL"                ',
    '               /aZrC@@@ZpZm@@@@Wo@&*%@@@@@@@@@@@@@@@kddB@@@@>x&Qkqvbbbw1_zkbJapw[               ',
    '             ~Umj}8@@#mah@@@@@B@B@@&B@@@@@@@@@@@@@@dmpo@@@@j((!{(LM#bv{(Zm<0WpZZa(              ',
    '            ro(Yk#aZfpwOk@@@@@@@@mo@@@@@@@@@@@@@@@@dmd&@M@k<| X*;-pz?XW0JjmZzCQB@Mj             ',
    '           XUtUpXOOa@@@@@@@@@@@@@)q@@@@@@@@@@@@@@#mdbaBB@@-UO i>{t+X@@dxXQ@@@Xrb@@@0.           ',
    '          U/&@vUbM@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@opwka@@W@x>@@@h(jO@@&h@*+Xu#@@qjM@@Xv`          ',
    '         Cc@@oqQ-8@8#*&@@%BB8W#@&8WW@@#o&@@@@%@@qpM@@@@@@ik@&v|vo8Wp**@@L/)xu/n)xv#d0C          ',
    '        {jxU%c|@k@@@@@@@@@@@@@@@@@@@@@@@@@@@@B@hmdpW&@@@1_pQ|U@@obka##hW@QUBatQOLj|m0qu         ',
    '       <{0qMXa@@@@WbmmOYvnrrr/]+i|@@dQpCnJZma@@@@@@@@8B@]{{q@@@B8WM@888B@@@@@&fczzafm@a1        ',
    '       {:;~<: \'                  q@&wv_i ~,<\'` "i-/Yq8@@@@@@&@@@@@@@@@BB8B@B%anQC@@@]8@p?       ',
    '                                /o@k#M%8*w`rW@@x)cXr)}{)um#@@W*#WM@@@@@@@8@L{&<JfQ@@B|@@Y       ',
    '                                ?&@vQoku@x :>tu*@&cLZcUm_;_r@@@@@@*kmoa&@@@@@@pL}w(kq(r@w{      ',
    '                                O@@Iz@hvd "l . jw8I>vCrI ]/U@8md&@@@@@Bbdp*8@%@@ZLt)mfYZBm;     ',
    '                               >kk@|-((@? i`.`";+}){+"   fxc@@h@@o@@@@&@@@@@@#&#@@Mcub|u@b~     ',
    '                                \'p@vnuh@"!I,\'"li:`",.  {xUCwkp&O@*k@@U.  ]w@@@@@@@jQ/oMJC@x     ',
    '                                 ld0uk@( ll. }?  \':}rucxftt0Z@@QOvh@px      ,(Q@@@cfqa@c-8n     ',
    '                                  /@(w@Y)cOQC~}[, `!/x(!>-]o@/;[fB@on           i|/zM!I/l~]     ',
    '                                  ;murJMoUtll")<:!\';1|]-I[{OBZO@@@@d"               `,[u]Cu     ',
    '                                 +zB8~W*qOqCx(U/:n-;)(1}](tUYv@@@XI                             ',
    '                                ;0}c@ru{8@@#c|-pvv!:{>l-(XB@ULt/@&<                             ',
    '                                cnj[@#]Lj![cX(jf_i\'"!?rmM@w{>\'.m|@j~                            ',
    '                               \'&8vJudkp>{: , .,!]fCp%wv+  "tY@Wx0JL                            ',
    '                          .    (@#CQnx@%@@@[+{fjcf)l,   .{JW@@@(mtd_                            ',
    '                         .     k*@Zx@|OovJZjc)".     -/La@@@@@prdv@_                            ',
    '                     \'\'   \'\'\' f8a@dr@w}8@OQmLr)(x0hW@@M@@@@@@@tp|oB!                            ',
    '           "\' `, .   :\' ;ii".|kqk@8X&@zt@@@@@@@@@@@#Umbk@@@@@@0L(@J;.i`.  \'.                    ',
    '             : . ,!l,`I++lI[0@@oB@@J@#@{n@@@@@@@@@@@#@@Bha@@@L@td@L{,,\' ``   :                  ',
    '        ,,   .`.i;;\'i>!`l(L8@8@@@@o*@&@#rd@@@@@@@@@@ppmZM@@@kM@v@@LvI!`   .\'   `                ',
    '          . ,: `;;,:.`!jBB8@@B@@@zn%@@8@U(f&@@@@@@@@@8B@8aCr/h?|w@8][--Il;i!,  ,,`\'             ',
    '      .   .\';;"\';, .+m@@@#dq*B8#@]d@@@&@m[bt-|cJCx|XUc///Yz|[mqjl<uYrx-+--+__i;  ,,,.           ',
    '     .\'     ."l! ;/*@@@@@@Xpa*&Ynpqd#QwQ(0qLCOcxnuz/{XvXu{XZuo@Ouq1{cU{{-+-?+~ll,\' .\'"":        ',
    '         \'\',\'  >c@@@@@@@@@w*O0}Z@pkakWoxc8xzfXpUX/YXQzc+jnrt:}W*Jnzm>/kx[(~-}]_>i",,   .!       ',
    '        .    (a@@B@&%B@@@@@JuXhMoOOOOfxcaf#CYcvqWI   ,;       kC*cru#(+8Qrx/_?[|-I<Ii`\' \'!      ',
    '      \'.  lv8@@88BB@@B@@@@@k8@p#b< r*wM@u@XQULt}cZx>lli~__I?}icZOkCd/wx-*&MU]-}|(]~_+~-+""l`    ',
    '        -Q@@@@B@%WWrh*pM@@@@pd)j@pUW*@@Zb0uvWda|/MB#]?/){]{[[lXmzmrcxrCt I/]>  ,:]}1]-[[}_+I    ',
    '     \'udbhmOpo@@@@@|dMabCo@@Mokp8@@Z@@d@@MQ@aoM/znmdUti<l:,\';.YX0XwO1c|[(~i((<{: t]){)_][]?]    ',
    '    +h&Lh@daowOO@@@@@8@*mCC*@C![u@b@&k@L#MqM#mzZOtc1|Yf:;{}_)<ch#pxfj)aUXZcfk@@p;]f[t{{1}{?[-   ',
    '    bkopp@ah@@B%p@@@@&@@kmXYm@B1mo@@#@%apQm8pLCoZkzYrr0Lx+_}(+X%kJtYJCcxntJC}n@@Q"c_UX)[{t({!,  ',
    '   -pJ0ddm#oM@bM*0YW@dt@@OXJXr*@m@8#@@CCcCcma@@Bo#LQUnXmZZ{~<i0ZzOaunf/UOUJmanfM@rZ/tUCX{(j/l.  ',
    '   zwY0qqJYQwhW8MWZj0@ojC8dCJ0*C@hY@@#&c0UczwJUYOMMuv{(pvwMY1~OdL0nCOZYu(?uXca0{qhjJ_0uZx[({,   ',
    '` -mctXqpLJLOw*h*@&8cY@@njhdh%Lz@uCpmOmmdhbmmdojJUc@uUU{UvmC#|ZwmCp#0vJzJvUuxCc*tY/p~OLQdj:"I`. ',
    '  0x1lLLpzCYQwaMUma&@0|@@dXW@&mnJ_(xJvxUXqpLUmqwOarpBWOuxuQUO)xddUuc(tOQwkZCQz(Y0fU*)paCQU +   \'',
    ' i|>_(JQYJJLmkm#WQqoh&n)@@XQ@@@@@@@@@B8bw#Q/uc(uxXUv0ZmmjQqmXb@L0cYQmqmmQC(nXCqZ*&t&}pmpQpJ+,   ',
    '  i!`"+cYUXzQmLCb*0qW@h(o@YC@WqZQX@@W@@@@B8@@@B*OLJvc(cuuvuQJY*pCpUwQLujCa@@@@@c8MZ&}hOv(tu/:   ',
    '   "    vjuncUz0ZmqjJ@%UX@Oo@ozt{0QJCJpwb@hQX*#@&@@@@8*8hz)|(U&OZOCvXbh@#wBW00CQb&MxLwYrj[(t+   ',
    '    ,.;  _(v((ucYLdk?k@OY@d@@f|Q#pXfYCmm0Yo@qunUq%#OkJvjjh#dUr@8L(X@h%xr{)JQJcCum&xYc||}>:I +   ',
    '        .  i/}~(Xf/r/xBUO@WBjx@@mnuJCQLJZ0XC@@mJpc_ z@|~>1t 1Qmwk@&C-fufrnpvn-~lCrux?I"         ',
    '             I}}c(r _-x}hmzzb@8crJzCQQ0CUQ0UXm@c{Omf\'u@wmmQ|x~:)U&p}|{0nx11   IccX"<            ',
    '            .\'    lr}(>nm+Yoq?<cZLLQpZCwqCCmZ0X0@Jn|vtn@qJt(  \'  <vnfXX[`        .              ',
    '             l\'\'\'   ;+_/?{x?I[t|-}}?rzctjuYQJqc{|nxl  ;:>x?`      .}}Ii`                        ',
    '               !;i     \'I             ``  `l>!_|)~/Ucl    `;         \'                          ',
    '                 \'   i                              I_`                                         ',
    '                       >\'>                                                                      ',
    '                                                                                                ',
    '                                                                                                ',
    '                                                                                                ',
    '                                                                                                ',
    '                                                                                                ',
    '                                                                                                ',
  ],
  [
    'zaQxOkYCZbvJaOzOkCLZkJcZwpXXZnUzYqpwmQbqOZmqb*dqqpZObaoZd0whZdddZpwaokQdkmZwhhkmhaZd*qdaphdqqpmq',
    'abXO&UxobLo#qmhhUqodJ0abmpqmUdB*foZZ0UQCZhdhLbLm#hbahkhaomkookooWomMo#W0daoohaWMao%awao*W&bbo&o*',
    'b(dbXzaOQd*LQ8mCdWdXkMkQrzX|a@@&_YQv[XZaoprZO-/qphobwbadpbdqqakaWbq#hmw8owdqabOb#Zhapkdaaq&Mhh&o',
    'cw#JxMCu&#cZoJuobcqpQYn[nLw\\WB8Xc1:l-fuYn/JJ~ux(hLcohodq*kZMoqpd#baqhhbpZqbdbWhp#W*p#qp#*kbWdwob',
    'vbUU#b/QdzkaOzhozhMOc}l)i?>l#81+"  ^\'.i! <(: >` "" :)Uwqdbbakqooowqhhpqqpbkaopp#aqokbkpqpkod%Mpa',
    'pO|daumaXnaCzoZrCpx]i \'    m@X              .     .   }db0QbqhwmaamLko0m#kwkWq0#ohaWhh*oqdoapo*p',
    'a\\r#rYMcOoJ/\\<`"^       , x@&;^l<i~<_-!"i!"\'   ....."l^>moabZwoaJJapbbMpwa#ph&omMhQbbdpohb#oJd&a',
    'L/W0x#wt0z<II.    .... \'l}B@Y}f0Cw*&@BoM@%#aQt"   ..  .\'?ZnZ#qLwbqUabwpa#koowmohw#bpabZbkdq&kpob',
    '{0WuXJ>>.              !<MB#u#dbOYrxfQ*&@@@@@@MY_.    .._jjYLdawqo*wwobaMpwhbkdMmk*wpakQh#XhbmWo',
    ')0/l!`   .. .       !(/-QM@Yvt~_[)(([; .Ira@@B@@@hz)l :  IxwpQwWdQMd0kWLbaOq#dX*pqoaQpomaM*bopw0',
    '-l    .          .>f0a{j@8W|/]xzvvX0*&C|l !L*&BB@@@@@dv? !_]qhJwWLU#QOhQQbh0dpUkoZqMkp*bmMdOcf]~',
    '`....           ,~-jwv}&W@YrUtx]?-![-(uYu\\JqW8%@B@B#M@@@c}CJ\\ObC#kfaquL#0m#QZWZU*pLhawaQXv|]-->+',
    '               \'I~|nX[ppWMv&MMB@@BopmLcvw%@@@@@@B&B8d0|l".l*O0aQmoY0o0momJ8q0#LC8dzMpJj}_<I!+_-~',
    '               `l?>j-Yo*@Ck@@@@@@@@@@@@@@BZUr}__~<{b@@JlOqOOuZM0O*mUadZ#YQhJZMZJWOxc1<-il~<><_<~',
    '           .   .l-}]v@B@Mn%B@@@@@@B@B@@hLi"I     \'i;-)-[(zJZ)f@c0WCz&0Z#Y0*JJoZQQ/-i!~~+i!><<~<!',
    '            .,I>tr{|@@B@YwB&@@@@@@@@@%UQw;,""`^~>,_I^  ^l|{/v-rrp#cbwzd#QJo0LkY1lI>I!<~>!>!>~>>i',
    '            "^I}t/]&@B%Mf@&&%B@@@@@@8Jm@@hqwooo%h/"."".^|aophL[UMUzWQUowvaqCu}>il>~!!>>II>!!><l!',
    '           .^:-\\v~Z@%%BX(LoB%%@@@@@&J#@@@@%Mbdba8%Lcc:;^Y@@@8h/hzn%qvhonJoX1!;I>!I<!II>II!!!!il:',
    '       .      .~[n@Bo&8|Y\\Y88B@@@@WQW@Bbx<I`I:!}(/tXOUY),Y@BBBb/JMY\\#*OLqz>!I>llIlIl,;I;"l",:IIi',
    '         .. .`+(-aB@#%YvJ0*8%B@@@@dM@Bc."f0bB8B@@hmz;;jaz?q@B@@QJLtpwYqa/`;Ii^;:>^<,:">^l.l`+ +.',
    '....         )Y+w@@B@o}pLUW%%%@@@@@@@/"jh@on\\--1{rb@Mf \\%p/8@BB@xzWY{qa/.<`l`! ,.i i`:.,\':.I"^: ',
    '      ....  :)-/@B%d&|fvrpB%BB@@@8B@YIuhc!         -a@{"o@qw@BM%hxQLkqz I`:\'l^!^::`"." : " `.`! ',
    '1|r~.    `""!;lb@B8@Qff|d@%BBB@@%&BBU<_             ;p(.m@8#@&&B#1bdzXl`!.;.> l i\'"".: l ;:.+ lI',
    'i`>;\'^rpr`,^`^L@BBB*1CfnwW8%&%@@Wm@WWqt|1|(}(uYvf};. O{.Y@B@%MB&M(ftaC :`^,\'l l I`\': ;.,I i`"~\'I',
    ' <(\\. ~nh: ` tB@@B@nvYYcr\\o%&B%BBZ0mOQZYnu/nh@@@@@Mz>u[ }@B@%8%8#tLUYt.I^`:.< ,"\'! +;.<.l>.!l"!,',
    'Q@@m-//\\@h:.:ZBBB@Z!YvOjr\\#W#8@@@WCXu/vucfL8BBBBBB@%*X}-nbB@B%B%8juuOU :< ! :l i.,!.l:`I,:i:I!;;',
    '@#X1[|u0CuI\'r8M888l.>fYxc(XCCxCh@@odM&awUk@@@@@@@@BBB*UXc0%B@B%8W/UwrX~ I\'.; !I.l,"l"I!"!l:I,;!;',
    '~,         }W@@#Bf \'`l)zcrvL(\\>^)m@%aW@B%B@@@@@@@@B8MvtX|zbB%n8W@f\\cUw/^._:"<`;i"!l,!,:I::IlI:lI',
    '  ........"Z@@8@k`... .]rzzL)x<  lc*@@@@@BBBBB@@@@@BBovcvc8@X(&&&}zCf/ZZ` <l"iI:!I;l":lilI:I""::',
    '.       . n888M#_ . ... ,<!^`\' .. .:1zkWB@@@@@@BBBBM*UjQp&&Y!ZX%d>Y0wdzfzt \'iII!";;:I;l;l:I:::;,',
    '       . lq&&&Bv . .          .       .,_{zmhM%@@@@%adob0U[I)/w@n]JtvJO0cjr|`\',;;;;;!;l;;,"II:;\'',
    '      . :LB@B@o"..    .  ..   .......\'.     \'"_\\zXufnt\\_"  IIz@W[rYLzcjzmQJzxji.`:I;!;"I;I;,:;l:',
    '      . {*@B%@}.. \'. ..     ...... .``...\'\'..            `;!?Wwu;cunzJJzj)zmQvfcc>,,,";::":^:,",',
    '     . +o&MB@Q \' \'.  ..  .\'.\'^\' . ..\'.. \'^..  \'\'.`\'....\'"`"<-}1:nLXXr|nuUJUnrmZz\\LOu]_}^ .":\'^:l',
    '      `cBB%8o: ...\'. \' \'...    \'. ... .\'.. ...  .`\'. \'`\'^``,li>;UujJLYJc\\nUZn)c0OX(u0dr-vY_I_<^\'',
    '    . 1h%B@@) `..\'.....\'. .  ..\'.. .  .  \'. .."".^,,\':^,l"^"l`lzYnJt(fXZ0x(fzZQj)xOX}[CdJtck0/1U',
    '     ,L@@%@q......  ...    \'.\'\' .\'\'\'...`.\'\',`\'";..\'`,^\'`":^I^"\\zccUCcn/fUJx|([uOLYr\\Umc1fQL(|wpv',
    '   .\'xWBBB&<`     \'\'......\'.. . .   .\'  ..\'\'^^,"^,"`;,`^;:, ;zznvt}rYCcntr/   ~]fUOZtxYCX/jLwv1J',
    '" . [o@@B@fI[~;,"\'\'. \' \'..\'\'\' ....\'\'\'.">"\',,^;>>i;^",,:",`l_\\vcrxvzvfrvYULx+:.  nxuYOYYtzmOj(JpL',
    'l\'.^U%BB@m"+(_l<,". \' .... ..  .\'"`:!_n(ttv/r?>!!!"^l:"` IjzYvfxx/YYzXYvjrvQ/>~, >0U}xLmQrn0Qc)z',
    '`: 188BB@<^]xv|:.^:\'\'.\' ..  .\'\'`,"l/vxvfcnrQcr)[>,\',l",1fffzvuYvjfxt/xzUvr(tnLq|"  <UQ(tY0x/?cwY',
    'l\'!C%@BB{\'<I[wJ(<^",^:",`.`^\'"I!`ifftrzrxcjf(r]_` .;, [rf\\jxtjvnzJccnnf\\xruXcj/cO-  `_Q0u|jUzx\\v',
    '><v8BB@h."i!!vCLt;`^",`,^``\'il"+ncn)vUz||u0z(\\_l ..\' _Junvcucnrtrc|xccYcr(/nvXc/)vc"  "iJOr((LmY',
    'n?*BBB@-.~>Ii)U||?l`,","",.>~:]vXOrXxc}!i_vmfx~, "`  lnx/jjuYuznn|\\jftuC0zv/1fJYzn(/)  .!>rpJ}fv',
    'Iw%%B@0`;-l>+l[Xc?:"\'``,",:l:i\\znYxcz|_ii!+nC(l.I~< .<Y|r/|f/f/tuxucznjrnvcXcn(|jYzzr~i  .~-jwzt',
    'x#B%@&l`+!<><<`]ct>!:"`.^\':^<l1f|nJzfn/];!{vz<.>x|+ `;(cfrxufrx|(|txnnxn/\\)rcvYJ//frUZfl`   -[(X',
    'mB&%@/`!l<[I]~:lvx-~IIl^;:":~>1jxzvfuY(<+?|Lv:>)xu~\'`;jr\\rxucxfxf(tr/)trjnun//\\xrcJr(tn0-  .  {\\',
    'B@%Bm^\'!!i{i>>-{zr!"!;",::;l?I1xrnjxu/j}i:{r{,<Uur_^ ,nr(ttjft(|cuvcj/\\/tfuzYUrt1tcUJjx|xY; ..  ',
    'BBB&!.\';_~l__II}z1>[I\'^`,^.!_!}Ynfvnunz)I<uj<`{U)f|i`>rt/ncnxr|/ttxtnxzurxnt\\\\vXcrfrrucYj[r/  ..',
    'W%@x . \';~;:!I:tY{!+!l~,Il">-<jfvuccUUYtl<Yn-+nnz|u;,+r//xrtrjuzzfjjnfftxrrn\\j(\\txvUntrxzYn([<  ',
    '&@h^\'.  . ;<il^tLx-?ilI!;,!!l(rftjxnYYrt<"/fi/cxt}v>,?xfjfft/\\ftnjruvnX/\\j/frznvu/\\nfcXr1rccU|>,',
    'BBl        ":~"1z/rCfr(>!I>>l)rCn/(unCzv1-nr}nuzfcxI;)nx|trnnrrttr/xxrrtvvv||(txcnxj}{nCJffffzO)',
    'wY(v/I       ""+trYn|tzxr)}ilf/nJn\\vcc)/f)U{\\vnYfrU~!?r\\fft\\fxxvrurtfftt|fcxtfr/|tfjuxx\\tnYr))tY',
    'ZlcqMW< .      .I(uXtnQnxurn\\XvxjuxfXzxnutj)1rCJxjr]+-xrtj///jfff\\unntjxf//t/xjnr/(jrnuzf(1tzJv1',
    '; ;XZ@u .         ">{fr)LUvX0ztfcfvQQUj\\/cLftULn(n/<l~jtrjft\\fttjt/ft|xjunff(rffjjzzf1(uzYz\\+.  ',
    'X<[zLBx .        .     ^<?{f/JrvvJJYnz|xYuCcnvYrxU1?~l)ftf/rtr|rffrjt\\/1)(fjjx/j(1jxrvu/_^    ..',
    '@8v:t@- .          ..        ,"+-~-/)1+[)_))_+-?vnvi<l{n\\1\\t//|/)jfrjrxf|fxf\\\\vzYut?l\'    ...   ',
    'B@@x?M`                ...         \'\'"^`,`:"^^.:I<?_I;^jxvcxf/tx)t|\\t/jnnYJuf1~;.     ...      .',
    '@8B&uZ .                       ...          ....   . . \':,_rfnnuzzcxf1[_!"       ...            ',
    'ULQtbY .            .                                     ,[-+>I^.                 .\'\'`^",,;;Il!',
    '."]U@Y .                       .           ......                \'`";I!><~?-]][][[}{[??--_+_~>>>',
    ' .:JMW" .                     \'v_.\'...             \'`,Ii~_?))1)|\\\\\\){[]?+<~lI;,^`\'.            .',
    ')>f-M@w`              .....    vQ      .^:!<-]})(|//|(1{]_<>l:"^`.              .. ..... ,,l:;l"',
    '@zfQZ8@m\'.    ....           `,[m?[(///t//){[+>I,^\'            \'... .`\'.....\'\'```^\'",":;;I!>l";;',
    'Jwtdrc@@i .        \'";<-]{|/tt/|??_>I,^.          \'..\'.`\'.\'.. .. ...``,^ II`^:;I";,:I:::I`^,``\'\'',
    'p&xzXXkB: .`:!+[{1\\t/(1]~l:^.         . .\'``^`.\'`\'\'....^\'....^,""\'`!::;ll!^,I;""",\'":,  `\' .`\'  ',
    'zkC\\jncC{1(({}_<l,`         ..\'"`\'`"`\'``.`,^.^\',\'"\'`.\'"^"^`\'`lI:,,;`:<I\':i` \'I.  ,. ."  ..  .\'  ',
    '/f1}[+l":`         . .\'\'.```` `,``^,`. .                  \'. ;> .I!  :: .i^.``.\'`\'..\'\' .. .\'. ..',
    '^          ...    \'\'`.``\'"\'\'..                         .`.`,Il""!, `,"..```^\'..\'  .. ..         ',
    '   ....      .`\'\'\'`...       . .  `\'              \'..`\'"^^I,"`^`.....`\' .\'    .                 ',
    '         .."`^^..           .   . .\'     .   ..  .\'`::``...\'\'  .\'   .                           ',
    '           \'.                                                                                   ',
  ],
];
