export const ASCII_COLS = 84;
export const ASCII_ROWS = 62;

export const ASCII_FRAMES: string[][] = [
  [
    '                                                                                    ',
    '                                \' ;> .                                              ',
    '                          .\'.,1l.,11\\ .                                             ',
    '                             -[rI,1"n< .                                            ',
    '                       ...l}^1"1)>1:):                                             .',
    '                          )||\\:i{n>"}".                                            .',
    '                      .+>\'?>[v_^[r?"()\'                                            .',
    '                     ..(<+~~lY<\'1xf!\\{ .                                           .',
    '                     \'.l_^Y/\'J[ j\\,>t- .                                           .',
    '                    .   1`L\\ zj;u[ ~t> .                                           \'',
    '                   ..;!`I>(\\.r+ c1\'[{+ .                                           .',
    '                   \'.|]{-{_{ )|:t+:{1, .                                           \'',
    '                   \' >{:Xmij`+_\'(;:{{..                                            \'',
    '                  ..\' [I"O+|Ii{l(}[\\[ \'                                            `',
    '                  ...;~x^it"t_f~[~Itj< .                                           \'',
    '                 ..\' 1Itw ]\\|~_!~!)~YU_   .                                        \'',
    '                .\'\'\'"v1 /f-n (I};-1c([}I\'.                                         .',
    '                \'\'\' _\\Y) -J++;?_-]1x|`<>_(1.                                       .',
    '                 \'\' tJI)t`/}]_:](?]+n\\][I"I.                                       .',
    '                 ..IX)r<l?Y+i~}1~?->{v|u                                           .',
    '                 . 1xj-1i{zf[~)[}+f(||~)...                                         ',
    '                 . ~|<?[+(j+_+\\>)+t/|1.}^        ..                                 ',
    '                  \'\'\\|-+<?j+-!)]][[}1]"_+ .                                         ',
    '                  \' <\\+-<<f)_-?\\?{))((;+_ \'.... .                                   ',
    '                  .\' |(_<<_r[++{)[/|[/i-{\'\'   .  \'.                                 ',
    '                  .\'.?r{++~-r><!\\\\[n)|I-+] _)}{\\[ ..                                ',
    '                   .\'`(?i~>i(}l~!1_|t\\![++fX(f?I\\[`                                 ',
    '                    . :\\(l[><v-+~[n1|j_-t)0{:?-<Iv?`.                               ',
    '                     . "(?(!I\\\\~-+|vjf(?j|)c+~+<ijc, .                              ',
    '                      . It?<?<ft_<i-ff\\!{t,If+]"}xl .                               ',
    '.                      \' [)<_<l}\\/|+<n?;:)l.I-~?)c .                                ',
    '.                       .\'>\\~?<<]|{}1f_?]] \'\'\'i>,), .                               ',
    '.                          l/|][[I!\\?X~/\\_>I.",`\';}> .                              ',
    '                          .  ,><-_/)rj1)l.l>:+~\'\'.+1".                              ',
    '                           .     \'  +(i__{il;!>+`[/?? \'                             ',
    '                             .... ..;|{{n<!;,><<fvr>_> ..                           ',
    '                                    i(\\/<ii__;~nf{x(I->\'                            ',
    '                                 . !r]]1~!;[+i/j\\-?}\\[j?l  .                        ',
    '                                 . zvt]}:i\\i!!n\\|)?-](?)]~^ ..                      ',
    '                                . lYYCct+ `;+]Xntn_~i[-}\\1_l. .                     ',
    '                                . )[fOZOCnfz)<tu}f)-~{-[}|/r-, .                    ',
    '                               . ;x</v0Lccnf_[?x)_\\f[([())tJt):..                   ',
    '                               \' [j_l)rzx[l[}~\'r1<1){tf[-?)zx+) \'.                  ',
    '                               \' }n|.itnu_{[;+\'{tu)>]{1rft1_1rx~ \'.                 ',
    '                               . -|ri`xct\\+ l?`-)+n\\/[}~]<)_)t[\\[ \'                 ',
    '                               . -|[<`>u l[I!{\'ix!?|[n/[1,["[l_)J[ \'              ..',
    '                                 ^f(-.;[. _)--~+|-1i{+/)v|{/_t1}xr~ .             ..',
    '                                . [t\\~[{ .^j|]\')v??-\\\'n;1>(]rl\\<_\\ul .             .',
    '                                \' ])/[\\+  >t}|+)nc,u\\~r^(\'/,j.I(^]vf..            ..',
    '                               .\' \\cnI/i I)\\11rI\'-+|t1/"j (\')[ ?| }n+ .            .',
    '                                . \\L?_i} :|]"}] . .  "\\:c~1-;z\'\');,(t`             .',
    '                                . !Ji?}i^])[?? ... .\' ,\\c]-u;n}._].ix<..            ',
    '                                .. f]:/ ;v(])\'. .  ... ,?/+t~lJ),|I\'/f .            ',
    '                                .. in"{  -J}[ .       .  ;1]{ nr _Ql<J; .           ',
    '                                .. "Y])`.]}t+ .        .\' `+\\([f]\'z|.(j .           ',
    '                                .. \'X)1! 1nt\'.           .   :11}?[n\\lcI .          ',
    '                                 ...x1i? :I                .     "~-i]t< .          ',
    '                                 ...rY{]:  .  .              .. \'     "             ',
    '                                 . ^zuj[`..                      .....  .           ',
    '                                    `":`                            . ...           ',
    '                                                                                    ',
    '                                                                                    ',
  ],
  [
    '                                                                                    ',
    '                                                                                    ',
    '                                                                                    ',
    '                                                                                    ',
    '                         ...     :<[\\\\xnJJuQLmCYn1]+l^    ...                       ',
    '                      ...   ^!]tcZb**kpkbpkaWkbwdOpLXvf1>`   ...                    ',
    '                   ...   ;[n0bkkkbdqQJJUCYnzuXzuQmkpQd#Mo0t+,   .                   ',
    '                 ..   :]nqWhbb0UYCQphoo*kX/uYxrqp0CLCpbQbhpJc/!` ..                 ',
    '               ..  ^_xw*dOUYOawwppqmWb&qujXmC|uwXbdQtrUtLmpqd0n):   .               ',
    '              .  "(JdwOCvOhoWaqpO**ammbOoUm@kXJc{/\\/(ut/jUJqbqxcu1l  .              ',
    '            .. ^1ZdYxvUmQqWdqbbh*M%&%&W&&%WWMMak0UpOuz\\YrhdQXOqk*&d\\I  .            ',
    '           .  -zQXYm0Qwb*bakoo*MM&%WMMMW*WoMopmwa&W%o|XLCqmakCcYZwqwC]. .           ',
    '         .. IfYnXh&*ddph*o*akakka*MM*WW*oo**bm0Od*oMx|UvQm0kpX{tCQwqqQ/" .          ',
    '        . .1nzcJoqqmmq&M**ooohkaoo*MMWWW**W*bQQwhh&C1{[r?uaUfrz0crQwZqar" .         ',
    '       . "\\zuQ0OOqdooW&MMM&M*XhMMWo*&WWWWWMbmOZdaah|n+~f?)fuOkLzL%bUXbMoL! .        ',
    '      . :tXqUJZwo#%&&&&&W&M&&aW&MMM**o*W&WbOQZdakMr\\MdY|tzZohbQfUO*WOUkWbu! .       ',
    '     . ^tX*aQJuo*hkh*oaooah**Wao*hkho*Woah0Odoaa*q]dWCvvObbqpkbcxfYucrYLq0Xi .      ',
    '      .-jXp0UWd##@@@@@@@@@##WaMWMMM@%%&WWkwqphha*)1QXvqadwqpdpkaLmbzXCCvXOwc" .     ',
    '    .\'~{zCYzZZLcnj/|1{}]?-+>iY@*OJvfcXXLLwbka*o**rjzkM*hkkhakhhaWW%*XYUwZXbaj` .    ',
    '     \'I"","`.               <pMpmXx}|?fjf}]\\jnX0mo&&hbbao*****ohhoQqnYYo@mz&h(..    ',
    '             .............\'.\\hWmdkp@x>f0pZZOLUxjr/rCh*ahkbdpho****QbzXrCp*XU&UI .   ',
    '      .......             ..t%bfahvw_>!>~ubm[rJXt~}fw*kkWMWabbqqdkoo*dYXfCxvwdt`..  ',
    '                         . iQaq\\zzkt;<!li+|/{}}>"!fuZobhhh&%MoaM&*okbbhb0z0zYaJ: .  ',
    '                          ..<wpnnCq-<<!i+>><_~i![tcJmphpapk*Z]:~tLk&%&*kUXLdUZp[..  ',
    '                            ._wUChnl-?>?}>Il~(fjtttcOpdLY0kdv^    ,_/JakvCO0c\\0[.   ',
    '                            . cQzmCnYzn)?}>li}j\\??{nk0\\uOWWC;.....    :+]u(?j[f-.   ',
    '                  ........ . ,|quJbZUr({r1~]<[\\(1}|x0Qq#Wqu>      ....    `I?_|l .  ',
    '             ..\'..\'\'\'\'.\'\'...IrX&LU0pahLxjz/j~[){1\\n00X0O%c^ .         ...           ',
    '        . ..\'^`^`\'\'``\'``\'`\'./n(mMnuzxXXf\\x\\?>?[(nJqC/]?xQh?, .\'..         ......    ',
    '        ..\'\'"^\'````^^^"""^^!pquvZqQ\\{>~~+-?{/xYYx1~l?fLpuCU+ ....                   ',
    '      \'\'.\'.`"\'\'`\'\'"^":;;,,")obUJrkaphY}1(\\/)?>l;;i(Yb%@cYuC;``\'.......              ',
    '    ...\'..\'"`^"",^""";;;;:lLh*vZJvh0QJvj-illll}xCp*&M#qzXQCI,:^`\'..  .              ',
    '   ....\'\'^:,,,":",II,:I!l;jbkWLZ*x0%bpdmQL0bhhah*MMMW@LQjav;II,^^^\'....             ',
    '  .\' .\'.`,;;II;IlIIii~++[cbph&wmopjb@@@@@@@#Mdphho*W@awXY%fii!;;;;::"`\'\'...         ',
    '  ...\'`,:",II;li>><~+?)uqaWMW%po*WLu*@##%%&M&ohkdkW@@waz*oz{i!;;;;;;;,^^`\'..\'.      ',
    '  ...\'";;;IlIli!!l>-\\QqhW*W%MZm%#oWXnmM%@%%##MohaobmzwUuboU}[-<>!ii::l;;:^`\'\'\'.     ',
    ' ..\'\',:":;li>!!l!-xw#@kqka*okno@WhaUrQxuXUCczJUzuxzn|LQj[/cjj1]]???~iIIll;:,`\'\'.    ',
    ' .\'\'";,"::I!>>>(Xb@%%@k0dkpLUZwbwm0nOLXXXnuuufnvvxxUcUo0nu)tvr){}[}]_<!lIIl!l^\'`\'   ',
    ' ...^"",;;;:~/Q&MW*MM%%bqJuOaqppmZc0LUuvQ0Y))ftf~]{)>lYdZczn)UJ/\\11{}]+<>!;;;!"\'\'\'  ',
    ' ..\'`,;;:l?upoohha*MM*#hU0bbOxt0LCm0QqUzuzm{":ll;:;;l"j0qJJCJ{zp0J/}1|1?-_~>i!>;\'\'\' ',
    '  \'^^":>|CkMhkbbqwdk*%&WbbJ0kj\\bk*kObzZmJtubO/?[}}[}}?fLL0YcuC))YY|_+?]}{{]}}?_+;^^.',
    ' .^`^+jYwqpbo*aaQcpmmqWMppQY*MhbWoa*mZkdaucQbC/-?+>>>i\\UQCQjcj\\~~[(__iI)((){{)}[>^^^',
    '..`,/OQmqOmZZwoWahbbqCLq*bxcOMb*h*phhdapCLYuXrc/<i?_--/mbQXn/QzYXfn0Ov+||/\\(((){[l^^',
    '```{ZZ0ZkwbopqqhW*kbhmUXQpqn0o%*WWpwmbkm0bmOJcrJJr}?1}fdqLXJUJcvYLcxmkv)ftvf|\\t\\[>""',
    '^\'^uCCO0QZmkppwLQhoYZkLXXcwWbWh&%wLCLCphhhdb0XrvZ0J|[-xmCZCzurzXzCwCcQdvz/vzc//f[I"\'',
    '^ ~JUCOQYYC0pppqLXp*LX0QU0pmMZqMbb0Z0C0OOL0wqYvxYYZZc/XqOQJZQXcf)uc0LncJcfnzJz|1_I"`',
    ',:uu(vQLXXYCmw0qppCZ%wYObaOv0tzJQJmmppmZdCZQZkwZjcYQCvvqZL0CnYL0XYcYvOcrLzuQUQ\\l<l:,',
    '._/]}nYYzXUQOdOQwkkXC@pUo%WkbZZmqZ0QqJcUzLQZUwbmLuLOCXZZ0CXUYmZZLvUCYJZLQCzwLCY{>^",',
    '\',>!>{nczcYLCLw0Qwaqnh*Xb%kbpk%MW&%#akahZLUYCJYUUYJL0LkqLO0ZZLXLwqM&%ZawmYUmYxvn_"\'`',
    '` ;I^"ifxuuczYL0UzdaU0WQ*oJnxLQCLZqbabqd*W*%&oqwmOcxxzbpOQJCmmqqpWbwOCpbwc0Cxt)\\]"\'\'',
    '^. ",:^,?\\f/rvzUOvXo00%d%CxJmLvcULLCQbbLXLpb0QbYcvmOUvaoLzmdpLcxxLJcurLZczr\\1+ll;:.\'',
    '^ . \'``,`;+1{tcxt\\/OYmMdCzkbJcYLCLUJJYOakUCv}-mC/\\X|]YYLqW0ntXxxnz\\]>?znt1~l".   `. ',
    '^ ..  .^"^^,i_}?[?1(fOzYwbJvYOQ0LJJJUUUCbOYCLjfwd0Uc\\?i-/Qz\\fUr)_i``;?1}!:.     .   ',
    '^ .     .."!,^^`;-}[frtYc)1vvcvcYzczcYJLXuQu1]}}uvu}!`^`\'l(j\\)<"\'\'`..  .\'  .        ',
    '^         .`,lI,. \':<~lll!!I;;:I_?-+?})(||1{/}:,^`Ii,` ...`Il`..     ..             ',
    '`            \'`;,^,\'.\'                ..`",",+-;\'. `^ . ..  \'.                      ',
    '`               .`"^;,;\'".^\'"`.... ...         . ....      .                        ',
    '                                                                                    ',
    '                                                                                    ',
    '                                                                                    ',
    '                                                                                    ',
    '                                                                                    ',
  ],
];
