// Rasterizes Natural Earth 110m land polygons into a bit mask for the sand map.
// usage: node scripts/world-mask.mjs path/to/ne_110m_land.geojson > lib/world-mask.ts
import { readFileSync } from "node:fs";

const W = 240;
const H = 110;
const LAT_TOP = 84;
const LAT_BOTTOM = -58; // drops antarctica

const geo = JSON.parse(readFileSync(process.argv[2], "utf8"));
const rings = [];
for (const f of geo.features) {
  const g = f.geometry;
  const polys = g.type === "Polygon" ? [g.coordinates] : g.coordinates;
  for (const poly of polys) for (const ring of poly) rings.push(ring);
}

const inside = (lon, lat) => {
  let hit = false;
  for (const ring of rings) {
    for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
      const [xi, yi] = ring[i];
      const [xj, yj] = ring[j];
      if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) hit = !hit;
    }
  }
  return hit;
};

const bits = new Uint8Array(Math.ceil((W * H) / 8));
let land = 0;
for (let y = 0; y < H; y++) {
  const lat = LAT_TOP - ((y + 0.5) / H) * (LAT_TOP - LAT_BOTTOM);
  for (let x = 0; x < W; x++) {
    const lon = -180 + ((x + 0.5) / W) * 360;
    if (inside(lon, lat)) {
      const i = y * W + x;
      bits[i >> 3] |= 1 << (i & 7);
      land++;
    }
  }
}

const b64 = Buffer.from(bits).toString("base64");
process.stdout.write(
  `// generated by scripts/world-mask.mjs from natural earth 110m land. ${land} land cells.\n` +
    `export const MASK_W = ${W};\nexport const MASK_H = ${H};\n` +
    `export const LAT_TOP = ${LAT_TOP};\nexport const LAT_BOTTOM = ${LAT_BOTTOM};\n` +
    `export const MASK_B64 =\n  "${b64}";\n`,
);
